# Site settings
title: DrinkBird
email: tasos@drinkbird.com
description: "Beating the mediocrity out of software. With a stick."
longdescription: "DrinkBird is a blog for software engineers that deeply care about their craft."
baseurl: ""
url: "http://blog.drinkbird.com"
locale: en_US

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title
gems: [jekyll-sitemap]

links:
  - title: Posts
    url: /posts/
    page-key: posts
  - title: Projects
    url: /projects/
    page-key: projects
  - title: Books
    url: /books/
    page-key: books
  - title: About
    url: /about/
    page-key: about

owner:
  name: Anastasios Piotopoulos
  disqus-shortname: drinkbird
  twitter: piotopoulos
  facebook: thedrinkbird
  #googleplus: 
  github: drinkbird
  stackoverflow: 2050674/drinkbird
  linkedin: piotopoulos
  #youtube: 
  google:
    analytics: UA-55022241-1

reads:
  softskills:
    title: "Soft Skills: The software developer's life manual"
    url: "http://geni.us/softskills"
    isbn: "1617292397"
  codecomplete:
    title: "Code Complete: A Practical Handbook of Software Construction"
    url: "http://geni.us/codecomplete"
    isbn: "0735619670"
  agileppp:
    title: "Agile Principles, Patterns, and Practices in C# (Robert C. Martin)"
    url: "http://geni.us/agileppp"
    isbn: "0131857258"
  cleancode:
    title: "Clean Code: A Handbook of Agile Software Craftsmanship"
    url: "http://geni.us/cleancode"
    isbn: "0132350882"
  pragmaticprogrammer:
    title: "The Pragmatic Programmer"
    url: "http://geni.us/pragmaticprogrammer"
    isbn: "020161622X"
  refactoring:
    title: "Refactoring: Improving the Design of Existing Code (Object Technology Series)"
    url: "http://geni.us/refactoring"
    isbn: "0201485672"
  hfdesignpatterns:
    title: "Head First Design Patterns"
    url: "http://geni.us/hfdesignpatterns"
    isbn: "0596007124"
  gofdp:
    title: "Design patterns: elements of reusable object-oriented software"
    url: "http://geni.us/gofdp"
    isbn: "0201633612"
  dpruby:
    title: "Design Patterns in Ruby"
    url: "http://geni.us/dpruby"
    isbn: "0321490452"
  97things:
    title: "97 Things Every Programmer Should Know"
    url: "http://geni.us/97things"
    isbn: "0596809484"
  csharpindepth:
    title: "C# in Depth"
    url: "http://geni.us/csharpindepth"
    isbn: "161729134X"
  aspnetmvc5:
    title: "Pro ASP.Net MVC 5 (Expert's Voice in ASP.Net)"
    url: "http://geni.us/aspnetmvc5"
    isbn: "1430265299"
  jsgoodparts:
    title: "JavaScript: The Good Parts"
    url: "http://geni.us/jsgoodparts"
    isbn: "0596517742"
  leanstartup:
    title: "The Lean Startup"
    url: "http://geni.us/leanstartup"
    isbn: "0307887898"
  steallikeanartist:
    title: "Steal Like An Artist"
    url: "http://geni.us/steallikeanartist"
    isbn: "0761169253"
  interactiondesign:
    title: "Interaction Design"
    url: "http://geni.us/interactiondesign"
    isbn: "1119020751"
  learnazure:
    title: "Learning Microsoft Azure"
    url: "http://geni.us/learnazure"
    isbn: "1782173374"
  thebigswitch:
    title: "The Big Switch"
    url: "http://geni.us/thebigswitch"
    isbn: "039334522X"
