# Site settings
title: DrinkBird
email: tasos@drinkbird.com
description: "Beating the mediocrity out of software with a stick"
baseurl: ""
url: "http://blog.drinkbird.com"
locale: en_US

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title
gems: [jekyll-sitemap]

links:
  - title: Posts
    url: /posts/
    page-key: posts
  - title: Projects
    url: /projects/
    page-key: projects
  - title: About me
    url: /about/
    page-key: about

#  - title: Resources
#    url: /resources/
#    page-key: resources

owner:
  name: Anastasios Piotopoulos
  disqus-shortname: drinkbird
  twitter: piotopoulos
  facebook: thedrinkbird
  #googleplus: 
  github: drinkbird
  stackoverflow: 2050674/drinkbird
  linkedin: piotopoulos
  #youtube: 
  google:
    analytics: UA-55022241-1