# Site settings
title: DrinkBird
email: tasos@drinkbird.com
description: "Beating the mediocrity out of software with a stick"
baseurl: ""
url: "http://blog.drinkbird.com"
locale: en_US

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title
gems: [jekyll-sitemap]

links:
  - title: Posts
    url: /posts/
    page-key: posts
  - title: Projects
    url: /projects/
    page-key: projects
  - title: About me
    url: /about/
    page-key: about

#  - title: Resources
#    url: /resources/
#    page-key: resources

owner:
  name: Anastasios Piotopoulos
  disqus-shortname: drinkbird
  twitter: piotopoulos
  facebook: thedrinkbird
  #googleplus: 
  github: drinkbird
  stackoverflow: 2050674/drinkbird
  linkedin: piotopoulos
  #youtube: 
  google:
    analytics: UA-55022241-1

books:
  - title: "Soft Skills: The software developer's life manual"
    url: "http://geni.us/softskills"
    isbn: "1617292397"
    tag: "softskills"
  - title: "Code Complete: A Practical Handbook of Software Construction"
    url: "http://geni.us/codecomplete"
    isbn: "0735619670"
    tag: "codecomplete"
  - title: "Clean Code: A Handbook of Agile Software Craftsmanship"
    url: "http://geni.us/cleancode"
    isbn: "0132350882"
    tag: "cleancode"
  - title: "The Pragmatic Programmer"
    url: "http://geni.us/pragmaticprogrammer"
    isbn: "020161622X"
    tag: "pragmaticprogrammer"
  - title: "Agile Principles, Patterns, and Practices in C# (Robert C. Martin)"
    url: "http://geni.us/agileppp"
    isbn: "0131857258"
    tag: "agileppp"
  - title: "Refactoring: Improving the Design of Existing Code (Object Technology Series)"
    url: "http://geni.us/refactoring"
    isbn: "0201485672"
    tag: "refactoring"
  - title: "Head First Design Patterns"
    url: "http://geni.us/hfdesignpatterns"
    isbn: "0596007124"
    tag: "hfdesignpatterns"
  - title: "97 Things Every Programmer Should Know"
    url: "http://geni.us/97things"
    isbn: "0596809484"
    tag: "97things"
  - title: "C# in Depth"
    url: "http://geni.us/csharpindepth"
    isbn: "161729134X"
    tag: "csharpindepth"
  - title: "Pro ASP.Net MVC 5 (Expert's Voice in ASP.Net)"
    url: "http://geni.us/aspnetmvc5"
    isbn: "1430265299"
    tag: "aspnetmvc5"
  - title: "JavaScript: The Good Parts"
    url: "http://geni.us/jsgoodparts"
    isbn: "0596517742"
    tag: "jsgoodparts"
  - title: "The Lean Startup"
    url: "http://geni.us/leanstartup"
    isbn: "0307887898"
    tag: "leanstartup"
  - title: "Steal Like An Artist"
    url: "http://geni.us/steallikeanartist"
    isbn: "0761169253"
    tag: "steallikeanartist"
  - title: "Interaction Design"
    url: "http://geni.us/interactiondesign"
    isbn: "1119020751"
    tag: "interactiondesign"
    